default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 100 } %>

development:
  <<: *default
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV.fetch("DB_PORT") { 5433 } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV.fetch("DB_NAME") { "outhad_server_development" } %>

test:
  <<: *default
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV.fetch("DB_NAME") { "outhad_server_test" } %>

production:
  <<: *default
  host: <%= ENV['DB_HOST'] %> 
  username: <%= ENV['DB_USERNAME'] %> 
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV.fetch("DB_NAME") { "outhad_server_production" } %>
